linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  govet:
    enable-all: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
